// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY_VYK5u5fIurEw_nn5ui5Y0yrhnqbBBU',
    appId: '1:641103722840:web:320a9d630dbf9b006e8d2d',
    messagingSenderId: '641103722840',
    projectId: 'planitt',
    authDomain: 'planitt.firebaseapp.com',
    storageBucket: 'planitt.appspot.com',
    measurementId: 'G-WSZENHK9CG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZ7PVOlVRu3Pcr4jyV4vJumuoAJ_X0kfM',
    appId: '1:641103722840:android:10b0bd011d2d9af36e8d2d',
    messagingSenderId: '641103722840',
    projectId: 'planitt',
    storageBucket: 'planitt.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3PqjjfkC4vPQuaHMKaO5fzv8PHW_zsg',
    appId: '1:641103722840:ios:2a133a832a76be4c6e8d2d',
    messagingSenderId: '641103722840',
    projectId: 'planitt',
    storageBucket: 'planitt.appspot.com',
    androidClientId: '641103722840-3ia9vj5q7kpd885ohmqnf2pagfsk4mbg.apps.googleusercontent.com',
    iosClientId: '641103722840-emuf3hd0o8cpg47hc7nhtgjoej734o1b.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDD3PqjjfkC4vPQuaHMKaO5fzv8PHW_zsg',
    appId: '1:641103722840:ios:c74e0cac21eb505a6e8d2d',
    messagingSenderId: '641103722840',
    projectId: 'planitt',
    storageBucket: 'planitt.appspot.com',
    androidClientId: '641103722840-3ia9vj5q7kpd885ohmqnf2pagfsk4mbg.apps.googleusercontent.com',
    iosClientId: '641103722840-pjp5btps2hgpo1r00obhtg0pevqjrbeo.apps.googleusercontent.com',
    iosBundleId: 'com.example.toDo.RunnerTests',
  );
}
